# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.mailer:
        class: AppBundle\Service\MailerService
        arguments: ["%notification.prefix%", "%notification.email_from%", "@mailer", "@translator"]

    app.menu_builders_chain:
        class: AppBundle\Service\MenuBuilderChain

    app.menu:
        class: AppBundle\Service\AppMenu
        tags:
            -  { name: atica_core.menu_builder }

    app.admin.menu:
        class: AppBundle\Service\AdminMenu
        autowire: true
        tags:
            -  { name: atica_core.menu_builder }

    app.head_department.menu:
        class: AppBundle\Service\HeadDepartmentMenu
        autowire: true
        tags:
            -  { name: atica_core.menu_builder }

    app.student_group.menu:
        class: AppBundle\Service\StudentGroupMenu
        autowire: true
        tags:
            -  { name: atica_core.menu_builder }

    app.student.menu:
        class: AppBundle\Service\StudentMenu
        arguments: ['@security.token_storage']
        tags:
            -  { name: atica_core.menu_builder }

    app.student_tracking.menu:
        class: AppBundle\Service\StudentTrackingMenu
        arguments: ['@security.authorization_checker', '@security.token_storage']
        tags:
            -  { name: atica_core.menu_builder }

    AppBundle\Form\Type\AgreementType:
        class: AppBundle\Form\Type\AgreementType
        arguments: ['@security.token_storage', '@doctrine']
        tags:
            - { name: form.type }

    app.entity.group_voter:
        class: AppBundle\Security\GroupVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.entity.agreement_voter:
        class: AppBundle\Security\AgreementVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    app.entity.user_voter:
        class: AppBundle\Security\UserVoter
        autowire: true
        public: false
        tags:
            - { name: security.voter }
